#!/usr/bin/env python3
"""
EfficientViT-B0/B1 ONNX → MXQ compile script
Runs inside the Mobilint qbcompiler Docker container.

Key settings:
  - backend="onnx"
  - in_dformats 미지정 (기본값 HWC): qbcompiler가 HWC 입력을 가정하고
      CPU/NPU 경계에서 레이아웃 변환 op을 자동 삽입함.
  - calib_hwc/          : HWC-ordered calibration tensors (shape: [224, 224, 3])

Directory layout (relative to npu/):
  compile/compile_hwc.py   ← this file
  compile/calib_hwc.txt    ← calibration file list (paths inside Docker)
  assets/calib_hwc/        ← HWC calibration tensors (generated by gen_calib_hwc.py)
  assets/onnx/*.onnx        ← input models (NCHW format)
  assets/mxq/*.mxq          ← output compiled models (HWC interface)

Docker run (mount host npu/ so that calib_hwc.txt absolute paths resolve):
  docker run -it --ipc=host --name qbcompiler \\
    -v /home/airlab_compression/npu:/home/airlab_compression/npu \\
    mobilint/qbcompiler:v0.9.0.2 /bin/bash

Then inside container:
  python3 /home/airlab_compression/npu/compile/compile_hwc.py
"""

import glob
import os
from qubee import mxq_compile

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))          # .../npu/compile
ASSETS_DIR = os.path.normpath(os.path.join(BASE_DIR, "..", "assets"))

CALIB_HWC_DIR = os.path.join(ASSETS_DIR, "calib_hwc")

hwc_files = sorted(glob.glob(os.path.join(CALIB_HWC_DIR, "*.npy")))
if not hwc_files:
    raise FileNotFoundError(f"No HWC calibration .npy files found in {CALIB_HWC_DIR}")

CALIB_TXT = os.path.join(BASE_DIR, "calib_hwc.txt")
with open(CALIB_TXT, "w") as f:
    f.write("\n".join(hwc_files) + "\n")
print(f"Calibration list: {len(hwc_files)} HWC files -> {CALIB_TXT}")

MXQ_DIR = os.path.join(ASSETS_DIR, "mxq")
os.makedirs(MXQ_DIR, exist_ok=True)

MODELS = [
    (
        os.path.join(ASSETS_DIR, "onnx", "efficientvit_b0_r224_timm_nchw.onnx"),
        os.path.join(MXQ_DIR, "efficientvit_b0_r224_timm_nchw.mxq"),
    ),
    (
        os.path.join(ASSETS_DIR, "onnx", "efficientvit_b1_r224_timm_nchw.onnx"),
        os.path.join(MXQ_DIR, "efficientvit_b1_r224_timm_nchw.mxq"),
    ),
    # 원본(mit-han-lab) repo 가중치 → export_original_to_onnx.py 로 생성한 ONNX
    (
        os.path.join(ASSETS_DIR, "onnx", "efficientvit_b0_original_r224_nchw.onnx"),
        os.path.join(MXQ_DIR, "efficientvit_b0_original_r224_nchw.mxq"),
    ),
    (
        os.path.join(ASSETS_DIR, "onnx", "efficientvit_b1_original_r224_nchw.onnx"),
        os.path.join(MXQ_DIR, "efficientvit_b1_original_r224_nchw.mxq"),
    ),
]

for onnx_path, mxq_path in MODELS:
    if not os.path.exists(onnx_path):
        print(f"\n[SKIP] ONNX 없음: {onnx_path}")
        continue

    if os.path.exists(mxq_path):
        print(f"\n[SKIP] 이미 존재: {mxq_path} (재컴파일하려면 파일 삭제)")
        continue

    print(f"\n{'='*60}")
    print(f"Compiling: {os.path.basename(onnx_path)}")
    print(f"  calib : {CALIB_TXT}")
    print(f"  output: {mxq_path}")
    print(f"{'='*60}")

    mxq_compile(
        model=onnx_path,
        calib_data_path=CALIB_TXT,
        save_path=mxq_path,
        backend="onnx",
        # in_dformats 미지정: 컴파일러 기본값(HWC)으로 동작.
        # 캘리브레이션과 추론 모두 HWC (224,224,3) 입력을 사용.
        quantize_method="Percentile",
        quantize_percentile=0.99999,
        is_quant_ch=False,
    )

    print(f"Saved: {mxq_path}")

print("\nAll done.")
