#!/usr/bin/env python3
"""
EfficientViT-B0/B1 PyTorch → MXQ compile script (backend="torch")
Runs inside the Mobilint qbcompiler Docker container.

ONNX 변환 없이 timm PyTorch 모델을 직접 컴파일.
컴파일러가 모델 구조를 직접 파싱하므로 ONNX 변환 과정의 포맷 문제를 피할 수 있음.

사전 요건 (Docker 안에서):
  pip install timm

Directory layout (relative to npu/):
  compile/compile_torch.py   ← this file
  compile/calib_hwc.txt      ← calibration file list
  assets/calib_hwc/          ← HWC calibration tensors (generated by gen_calib_hwc.py)
  assets/mxq/*.mxq           ← output compiled models

Docker run:
  docker run -it --ipc=host --name qbcompiler \\
    -v /home/airlab_compression/npu:/home/airlab_compression/npu \\
    mobilint/qbcompiler:v0.9.0.2 /bin/bash

Then inside container:
  pip install timm
  python3 /home/airlab_compression/npu/compile/compile_torch.py
"""

import glob
import os
import torch
import timm
from qbcompiler import mxq_compile

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.normpath(os.path.join(BASE_DIR, "..", "assets"))

CALIB_HWC_DIR = os.path.join(ASSETS_DIR, "calib_hwc")

hwc_files = sorted(glob.glob(os.path.join(CALIB_HWC_DIR, "*.npy")))
if not hwc_files:
    raise FileNotFoundError(f"No HWC calibration .npy files found in {CALIB_HWC_DIR}")

CALIB_TXT = os.path.join(BASE_DIR, "calib_hwc.txt")
with open(CALIB_TXT, "w") as f:
    f.write("\n".join(hwc_files) + "\n")
print(f"Calibration list: {len(hwc_files)} HWC files -> {CALIB_TXT}")

MXQ_DIR  = os.path.join(ASSETS_DIR, "mxq")
PT_DIR   = os.path.join(ASSETS_DIR, "torch")
os.makedirs(MXQ_DIR, exist_ok=True)

feed_dict = {"x": torch.randn(1, 3, 224, 224).cpu()}

COMPILE_ARGS = dict(
    calib_data_path=CALIB_TXT,
    backend="torch",
    feed_dict=feed_dict,
    quantization_method=0,   # WChALayer: per-channel weight, per-layer activation
    quantization_mode=2,     # histogram
    hist_search_type=2,      # kl-divergence
    quantization_output=0,   # Layer: per-layer output quantization
)


def compile_model(model, mxq_path, label):
    if os.path.exists(mxq_path):
        print(f"\n[SKIP] 이미 존재: {mxq_path} (재컴파일하려면 파일 삭제)")
        return
    print(f"\n{'='*60}")
    print(f"Compiling: {label}")
    print(f"  output: {mxq_path}")
    print(f"{'='*60}")
    mxq_compile(model=model, save_path=mxq_path, **COMPILE_ARGS)
    print(f"Saved: {mxq_path}")


# ── 1. timm pretrained 모델 ───────────────────────────────────────────────────
TIMM_MODELS = [
    ("efficientvit_b0.r224_in1k", os.path.join(MXQ_DIR, "efficientvit_b0_r224_timm.mxq")),
    ("efficientvit_b1.r224_in1k", os.path.join(MXQ_DIR, "efficientvit_b1_r224_timm.mxq")),
]

for model_name, mxq_path in TIMM_MODELS:
    model = timm.create_model(model_name, pretrained=True)
    model.eval().cpu()
    compile_model(model, mxq_path, model_name)


# ── 2. 원본(mit-han-lab) .pt 모델 ────────────────────────────────────────────
import sys
sys.path.insert(0, "/workspace/efficientvit2026")  # 패키지 경로

ORIGINAL_MODELS = [
    (os.path.join(PT_DIR, "efficientvit_b0_original.pt"),
     os.path.join(MXQ_DIR, "efficientvit_b0_original.mxq")),
    (os.path.join(PT_DIR, "efficientvit_b1_original.pt"),
     os.path.join(MXQ_DIR, "efficientvit_b1_original.mxq")),
]

for pt_path, mxq_path in ORIGINAL_MODELS:
    if not os.path.exists(pt_path):
        print(f"\n[SKIP] .pt 없음: {pt_path}")
        continue
    model = torch.load(pt_path, map_location="cpu", weights_only=False)
    model.eval().cpu()
    compile_model(model, mxq_path, os.path.basename(pt_path))


print("\nAll done.")
