#!/usr/bin/env python3
"""
EfficientViT-B0/B1 PyTorch → MXQ compile script (backend="torch")
Runs inside the Mobilint qbcompiler Docker container.

ONNX 변환 없이 timm PyTorch 모델을 직접 컴파일.
컴파일러가 모델 구조를 직접 파싱하므로 ONNX 변환 과정의 포맷 문제를 피할 수 있음.

사전 요건 (Docker 안에서):
  pip install timm

Directory layout (relative to npu/):
  compile/compile_torch.py   ← this file
  compile/calib_hwc.txt      ← calibration file list
  assets/calib_hwc/          ← HWC calibration tensors (generated by gen_calib_hwc.py)
  assets/mxq/*.mxq           ← output compiled models

Docker run:
  docker run -it --ipc=host --name qbcompiler \\
    -v /home/airlab_compression/npu:/home/airlab_compression/npu \\
    mobilint/qbcompiler:v0.9.0.2 /bin/bash

Then inside container:
  pip install timm
  python3 /home/airlab_compression/npu/compile/compile_torch.py
"""

import glob
import os
import torch
import timm
from qbcompiler import mxq_compile

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.normpath(os.path.join(BASE_DIR, "..", "assets"))

CALIB_HWC_DIR = os.path.join(ASSETS_DIR, "calib_hwc")

hwc_files = sorted(glob.glob(os.path.join(CALIB_HWC_DIR, "*.npy")))
if not hwc_files:
    raise FileNotFoundError(f"No HWC calibration .npy files found in {CALIB_HWC_DIR}")

CALIB_TXT = os.path.join(BASE_DIR, "calib_hwc.txt")
with open(CALIB_TXT, "w") as f:
    f.write("\n".join(hwc_files) + "\n")
print(f"Calibration list: {len(hwc_files)} HWC files -> {CALIB_TXT}")

MXQ_DIR = os.path.join(ASSETS_DIR, "mxq")
os.makedirs(MXQ_DIR, exist_ok=True)

# timm 모델명 → MXQ 저장 경로
MODELS = [
    (
        "efficientvit_b0.r224_in1k",
        os.path.join(MXQ_DIR, "efficientvit_b0_r224_timm.mxq"),
    ),
    (
        "efficientvit_b1.r224_in1k",
        os.path.join(MXQ_DIR, "efficientvit_b1_r224_timm.mxq"),
    ),
]

# timm EfficientViT forward 시그니처: forward(self, x) → feed_dict key = "x"
feed_dict = {"x": torch.randn(1, 3, 224, 224).cpu()}

for model_name, mxq_path in MODELS:
    if os.path.exists(mxq_path):
        print(f"\n[SKIP] 이미 존재: {mxq_path} (재컴파일하려면 파일 삭제)")
        continue

    print(f"\n{'='*60}")
    print(f"Compiling (torch backend): {model_name}")
    print(f"  calib : {CALIB_TXT}")
    print(f"  output: {mxq_path}")
    print(f"{'='*60}")

    model = timm.create_model(model_name, pretrained=True)
    model.eval().cpu()

    mxq_compile(
        model=model,
        calib_data_path=CALIB_TXT,
        save_path=mxq_path,
        backend="torch",
        feed_dict=feed_dict,
        quantization_method=0,   # WChALayer: per-channel weight, per-layer activation
        quantization_mode=2,     # histogram
        hist_search_type=2,      # kl-divergence
        quantization_output=0,   # Layer: per-layer output quantization
    )

    print(f"Saved: {mxq_path}")

print("\nAll done.")
